RestApiId:
  Value:
    Ref: ApiGatewayRestApi
  Export:
    Name: ${self:service}-${self:custom.stage}-rest-api-id

RootResourceId:
  Value:
    Fn::GetAtt:
      - ApiGatewayRestApi
      - RootResourceId
  Export:
    Name: ${self:service}-${self:custom.stage}-root-resource-id
